version: "3.8"
services:
    juice-shop:
        image: juice-shop:latest
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        ports:
            - '80:3000'